### ISSUE TITLE
ошибки после запуска

### ISSUE THREAD

**Issue by zazzik** [Elchinchel/ICAD-Longpoll#2]
18:34:57 Произошла ошибка!
Traceback (most recent call last):
  File "E:\icad_lp\start.py", line 69, in <module>
    asyncio.get_event_loop().run_until_complete(
  File "C:\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "E:\icad_lp\poller.py", line 40, in listen_longpoll
    async for update in lp.listen():
  File "E:\icad_lp\lib\vkmini\user_longpoll.py", line 63, in listen
    for update in await self.check:
  File "E:\icad_lp\lib\vkmini\user_longpoll.py", line 37, in check
    data = await longpoll_get(
  File "E:\icad_lp\lib\vkmini\request.py", line 23, in longpoll_get
    raise NetworkError(resp.status)
lib.vkmini.exceptions.NetworkError: 404

**Comment by Elchinchel** [comment]
Не используй VK Me токен. Пометка добавлена в конфиг
